"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Mail, MapPin, Menu, Phone, X } from "lucide-react";

export function Logo(){return <a href="/" className="logo" aria-label="NeoHold Invest начало"><img className="logo-mark" src="/brand/neohold-mark.png" alt=""/><span><b>NEOHOLD</b><small>INVEST</small></span></a>}
export function Header(){
  const [open,setOpen]=useState(false);
  const [scrolled,setScrolled]=useState(false);
  const [path,setPath]=useState("");
  useEffect(()=>{const sync=()=>setScrolled(window.scrollY>24);sync();setPath(window.location.pathname);window.addEventListener("scroll",sync,{passive:true});return()=>window.removeEventListener("scroll",sync)},[]);
  useEffect(()=>{document.body.classList.toggle("nav-open",open);const close=(event:KeyboardEvent)=>event.key==="Escape"&&setOpen(false);const closeWide=()=>window.innerWidth>1024&&setOpen(false);window.addEventListener("keydown",close);window.addEventListener("resize",closeWide);return()=>{document.body.classList.remove("nav-open");window.removeEventListener("keydown",close);window.removeEventListener("resize",closeWide)}},[open]);
  const links=[["/","Начало"],["/#about","За нас"],["/portfolio","Проекти"],["/#principles","Подход"],["/#partners","Партньори"],["/#contact","Контакти"]];
  const active=(href:string)=>href==="/portfolio"?path==="/portfolio":href==="/"?path==="/":false;
  return <header className={`header${scrolled?" header-scrolled":""}${open?" menu-open":""}`}><div className="container nav"><Logo/><nav id="primary-navigation" className={open?"nav-links open":"nav-links"} aria-label="Основна навигация">{links.map(([href,label])=><a className={active(href)?"nav-link active":"nav-link"} aria-current={active(href)?"page":undefined} href={href} key={href} onClick={()=>setOpen(false)}><span>{label}</span></a>)}<a className="nav-cta" href="/#contact" onClick={()=>setOpen(false)}><span>Изпратете запитване</span><span className="nav-cta-icon"><ArrowRight size={16}/></span></a></nav><button type="button" className="menu" aria-controls="primary-navigation" aria-label={open?"Затвори менюто":"Отвори менюто"} aria-expanded={open} onClick={()=>setOpen(current=>!current)}>{open?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}</button></div></header>
}
export function Footer(){return <footer><div className="container footer-main"><div><Logo/><p>Инвестиционна компания за модерни жилищни сгради, редови къщи и бутикови комплекси.</p></div><div><h4>Навигация</h4><a href="/#about">За нас</a><a href="/portfolio">Проекти</a><a href="/#partners">Партньори</a><a href="/#contact">Контакти</a></div><div><h4>Правна информация</h4><a href="/privacy-policy">Лични данни</a><a href="/terms-conditions">Условия за ползване</a><a href="/accessibility-statement">Достъпност</a></div><div><h4>Контакт</h4><a href="tel:+359887102828">+359 887 102 828</a><a href="mailto:ofiice@neoholdinvest.bg">ofiice@neoholdinvest.bg</a><span>гр. София, ж.к. Иван Вазов<br/>ул. „Краище“, бл. 16</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} NeoHold Invest. Всички права запазени.</span><span>Инвестиционните решения изискват индивидуална оценка на риска.</span></div></footer>}
export function ContactSection(){return <section className="contact section" id="contact"><div className="container contact-grid"><div><div className="eyebrow light"><span/> Свържете се с нас</div><h2>Нека обсъдим<br/><em>следващата възможност.</em></h2><p>За информация относно проект „Лозана“, партньорство или инвестиционна идея — изпратете кратко запитване.</p><div className="contact-lines"><a href="tel:+359887102828"><Phone size={18}/>+359 887 102 828</a><a href="mailto:ofiice@neoholdinvest.bg"><Mail size={18}/>ofiice@neoholdinvest.bg</a><span><MapPin size={18}/>София, ж.к. Иван Вазов, ул. „Краище“, бл. 16</span></div></div><form className="contact-form" onSubmit={e=>e.preventDefault()}><div className="two"><label>Име<input required autoComplete="name" placeholder="Вашето име"/></label><label>Телефон<input inputMode="tel" autoComplete="tel" placeholder="+359"/></label></div><label>Имейл<input type="email" required autoComplete="email" placeholder="name@company.bg"/></label><label>Тема<select defaultValue=""><option value="" disabled>Изберете тема</option><option>Интерес към проект „Лозана“</option><option>Инвестиционно партньорство</option><option>Друго</option></select></label><label>Съобщение<textarea rows={4} placeholder="Разкажете ни накратко..."/></label><button className="btn btn-copper" type="submit">Изпрати запитване <ArrowRight size={17}/></button></form></div></section>}
export function LegalPage({title,updated,children}:{title:string,updated:string,children:React.ReactNode}){return <><Header/><main className="legal"><div className="container legal-head"><div className="eyebrow"><span/> Правна информация</div><h1>{title}</h1><p>Последна актуализация: {updated}</p></div><div className="container legal-body">{children}</div></main><Footer/></>}
